site_name: DeadChest Documentation
site_url: https://stellionix.github.io/Deadchest/
repo_url: https://github.com/stellionix/Deadchest
repo_name: stellionix/Deadchest

plugins:
  - search
  - stellionix-shared-docs

theme:
  name: material
  logo: assets/images/deadchest-logo-small.png
  favicon: assets/images/deadchest-logo-small.png

nav:
  - Getting Started:
      - Home: index.md
      - Download: download.md
      - Installation: installation.md
      - How It Works: how-it-works.md
  - Administration:
      - Configuration: configuration.md
      - Commands and Permissions: commands-and-perms.md
      - Customization: customization.md
      - WorldGuard Integration: worldguard.md
      - Troubleshooting: troubleshooting.md
  - Developer:
      - Architecture: architecture.md
      - API: api.md
      - Contribution: contribution.md
